const meals = [
  {name:'Uttapam', cuisine:'Indian', diet:'Veg', time:'25 min', serves:'2', desc:'Savory rice pancake topped with onion, tomato, and coriander.', ingredients:['1 cup rice batter','1/2 cup onion, finely chopped','1/2 cup tomato, finely chopped','2 tbsp coriander','2 tsp oil','Salt to taste'], steps:['Heat a tawa and lightly grease it with oil.','Pour a ladle of batter and spread into a medium circle.','Top with onion, tomato, and coriander.','Cook on medium heat until the base turns golden.','Flip once and cook the other side briefly. Serve hot with chutney.']},
  {name:'Roti + Bhindi + Salad + Dahi', cuisine:'Indian', diet:'Veg', time:'35 min', serves:'2', desc:'A balanced everyday plate with soft rotis, spiced okra, fresh salad, and yogurt.', ingredients:['2 cups wheat flour','250g bhindi','1 onion','1 tomato','1 cucumber','200g dahi','2 tbsp oil','Cumin, turmeric, coriander powder, salt'], steps:['Knead wheat flour into a soft dough and rest it for 10 minutes.','Wash and dry bhindi well, then slice into small pieces.','Cook bhindi with oil and spices until it becomes tender and slightly crisp.','Chop onion, tomato, and cucumber for a simple salad.','Roll and cook rotis on a hot tawa, then serve with bhindi, salad, and dahi.']},
  {name:'Pav Bhaji', cuisine:'Indian', diet:'Veg', time:'40 min', serves:'2', desc:'Classic street-style mashed vegetable curry served with buttery pav.', ingredients:['4 pav buns','2 potatoes','1 cup mixed vegetables','3 tomatoes','2 onions','2 tbsp butter','Pav bhaji masala','Salt to taste'], steps:['Boil potatoes and mixed vegetables until soft. Mash lightly and keep aside.','Sauté onion in butter until soft, then add tomatoes and pav bhaji masala.','Add the mashed vegetables and cook until thick and well blended.','Butter the pav buns and toast them on a pan until golden.','Serve bhaji hot with pav, chopped onion, and lemon.']},
  {name:'Paneer Bhurji + Paratha + Chaas', cuisine:'Indian', diet:'Veg', time:'30 min', serves:'2', desc:'Scrambled paneer with soft parathas and chilled chaas.', ingredients:['200g paneer','1 onion','1 tomato','1 capsicum','2 cups wheat flour','300ml buttermilk','Ghee, cumin, chili powder, salt'], steps:['Knead wheat flour into a soft dough and rest it.','Crumble paneer and sauté onion, tomato, and capsicum in ghee.','Add paneer and spices, then cook for 4 to 5 minutes.','Roll and cook parathas on a hot pan with ghee.','Mix buttermilk with roasted cumin and salt to make chaas. Serve everything together.']},
  {name:'Vaghareli Khichdi', cuisine:'Indian', diet:'Veg', time:'30 min', serves:'2', desc:'Comforting one-pot rice and lentils with a Gujarati-style tempering.', ingredients:['1/2 cup rice','1/4 cup moong dal','1 potato','1/2 cup peas','1 tsp cumin seeds','1 tsp ghee','Turmeric, salt, pepper'], steps:['Wash rice and moong dal together until the water runs clear.','Heat ghee and add cumin seeds, then sauté potato cubes and peas for 2 minutes.','Add rice, dal, turmeric, salt, pepper, and 3 cups water.','Pressure cook until soft and creamy, or simmer until fully cooked.','Serve warm with masala chaas or papad.']},
  {name:'Mix Veg Millet Paratha', cuisine:'Indian', diet:'Veg', time:'30 min', serves:'2', desc:'Healthy stuffed paratha made with millet flour and mixed vegetables.', ingredients:['1 cup bajra or jowar flour','1 carrot','1/2 cup beans','1/2 cup peas','2 tsp oil','Salt, chili, coriander powder'], steps:['Steam or lightly boil the vegetables, then chop them finely.','Mix with spices and a little oil to make the stuffing.','Knead millet flour with warm water into a soft dough.','Roll, fill, and seal the dough, then flatten gently.','Cook on a hot tawa with a little oil until both sides brown.']},
  {name:'Jeera Rice + Dal Fry + Chaas', cuisine:'Indian', diet:'Veg', time:'30 min', serves:'2', desc:'Simple rice, tempered dal, and refreshing chaas.', ingredients:['1 cup rice','1/2 cup toor dal','1 tsp cumin seeds','1 onion','2 garlic cloves','1 cup curd','Salt, turmeric, chili'], steps:['Cook rice separately with a little salt and keep warm.','Pressure cook toor dal with turmeric until soft.','Prepare a tempering using ghee, cumin, garlic, and chili, then pour it over the dal.','Mix curd with water, salt, and roasted cumin for chaas.','Serve dal with jeera rice and chilled chaas.']},
  {name:'Masala Dosa', cuisine:'Indian', diet:'Veg', time:'45 min', serves:'2', desc:'Crisp dosa stuffed with spiced potato filling.', ingredients:['Dosa batter','2 potatoes','1 onion','Mustard seeds','Curry leaves','Turmeric','Oil','Salt'], steps:['Boil potatoes, mash them, and set aside.','Make a filling with mustard, curry leaves, onion, turmeric, and salt.','Heat a tawa, spread dosa batter thinly, and cook until crisp.','Place potato filling in the center and fold.','Serve with chutney and sambar.']},
  {name:'Daal Dhokli', cuisine:'Indian', diet:'Veg', time:'50 min', serves:'2', desc:'Soft wheat dumplings simmered in spiced dal gravy.', ingredients:['1/2 cup toor dal','1 cup wheat flour','1 tsp ghee','1 tomato','1 tsp jaggery','Cumin, mustard, turmeric, chili, salt'], steps:['Cook toor dal until tender with turmeric and tomato.','Mix wheat flour with spices and water to make a firm dough.','Roll and cut the dough into small diamond-shaped pieces.','Add the pieces to the boiling dal and cook until soft.','Finish with ghee tempering and serve warm.']},
  {name:'Thepla + Chai', cuisine:'Indian', diet:'Veg', time:'20 min', serves:'2', desc:'Soft spiced flatbread served with tea.', ingredients:['1 cup wheat flour','1/2 cup methi leaves','2 tsp yogurt','Spices, salt','Tea leaves','Milk','Sugar'], steps:['Combine flour, methi, yogurt, spices, and water into a soft dough.','Roll small discs and cook each thepla on a hot tawa.','Brew chai with tea leaves, milk, and sugar.','Serve thepla hot with chai.']},
  {name:'Bengaluru-Style Ghee Roast Dosa', cuisine:'Indian', diet:'Veg', time:'25 min', serves:'2', desc:'Thin dosa roasted with ghee for a crisp, rich finish.', ingredients:['Dosa batter','2 tbsp ghee','Chutney of choice'], steps:['Heat a flat pan until hot.','Spread dosa batter in a spiral motion.','Drizzle ghee around the edges and over the top.','Cook until crisp and lightly browned.','Fold and serve immediately with chutney.']},
  {name:'Chicken Curry with Roti', cuisine:'Indian', diet:'Non-Veg', time:'45 min', serves:'2', desc:'Deeply spiced chicken curry with soft roti.', ingredients:['200g chicken','1 onion','2 tomatoes','1 tsp ginger garlic paste','1 tsp coriander powder','1/2 tsp turmeric','1 tsp garam masala','2 cups wheat flour','Oil, salt'], steps:['Knead wheat flour and rest the dough for rotis.','Brown onions in oil, then add ginger garlic paste.','Add tomatoes and spices, and cook until the masala releases oil.','Add chicken and stir well so it is fully coated.','Add water, cover, and simmer until the chicken becomes tender.','Make rotis and serve hot.']},
  {name:'Butter Chicken Rice Bowl', cuisine:'Indian', diet:'Non-Veg', time:'40 min', serves:'2', desc:'Creamy butter chicken gravy over rice.', ingredients:['250g chicken','1 cup cooked rice','2 tbsp butter','1/2 cup tomato puree','2 tbsp cream','Ginger garlic paste','Garam masala','Salt'], steps:['Marinate chicken lightly with ginger garlic paste and salt.','Cook chicken in butter until lightly browned.','Add tomato puree and spices, then simmer until thick.','Stir in cream and cook for another 2 minutes.','Serve over warm rice with coriander on top.']},
  {name:'Chicken Hakka Noodles', cuisine:'Indian', diet:'Non-Veg', time:'25 min', serves:'2', desc:'Stir-fried noodles with chicken and vegetables.', ingredients:['1 packet noodles','120g chicken','1/2 cup cabbage','1/2 cup carrot','Soy sauce','Oil','Pepper','Salt'], steps:['Boil noodles, drain, and toss with a little oil.','Stir-fry chicken until cooked through.','Add vegetables and cook for 2 to 3 minutes.','Add noodles, soy sauce, pepper, and salt.','Toss on high heat and serve immediately.']},
  {name:'Fish Curry with Rice', cuisine:'Indian', diet:'Non-Veg', time:'45 min', serves:'2', desc:'Tangy fish curry with steamed rice.', ingredients:['250g fish','1 onion','2 tomatoes','Tamarind water','Turmeric','Chili','Coriander powder','Rice'], steps:['Marinate fish with turmeric and salt.','Cook onion and tomatoes with spices until soft.','Add tamarind water and simmer into a curry base.','Gently add fish pieces and cook until tender.','Serve with hot steamed rice.']},
  {name:'Mutton Keema Pav', cuisine:'Indian', diet:'Non-Veg', time:'50 min', serves:'2', desc:'Spiced minced mutton served with toasted pav.', ingredients:['250g mutton keema','4 pav','1 onion','2 tomatoes','Ginger garlic paste','Keema masala','Butter','Salt'], steps:['Cook onions in oil until golden.','Add ginger garlic paste, tomatoes, and keema masala.','Add mutton keema and sauté until browned.','Add a little water and simmer until cooked and dry.','Toast pav in butter and serve with keema.']},
  {name:'Egg Curry + Rice', cuisine:'Indian', diet:'Non-Veg', time:'35 min', serves:'2', desc:'Boiled eggs in a rich onion-tomato gravy.', ingredients:['4 eggs','1 onion','2 tomatoes','1 tsp ginger garlic paste','Turmeric','Garam masala','Rice','Oil','Salt'], steps:['Boil and peel the eggs.','Make an onion-tomato gravy with ginger garlic paste and spices.','Add water and simmer until the gravy thickens.','Add eggs and cook for 5 more minutes.','Serve with rice.']},
  {name:'Methi Chicken + Roti', cuisine:'Indian', diet:'Non-Veg', time:'40 min', serves:'2', desc:'Chicken cooked with fresh fenugreek and warm spices.', ingredients:['200g chicken','1 cup methi leaves','1 onion','1 tomato','Ginger garlic paste','Chili, coriander powder','Wheat flour'], steps:['Wash and chop methi leaves.','Cook onion and tomato with ginger garlic paste until soft.','Add chicken and spices, then cook until nearly done.','Stir in methi leaves and cook for 5 more minutes.','Serve with fresh rotis.']},
  {name:'Mushroom Chicken Pepper Fry', cuisine:'Indian', diet:'Non-Veg', time:'30 min', serves:'2', desc:'Dry-style pepper chicken with mushrooms.', ingredients:['200g chicken','1 cup mushrooms','1 onion','Black pepper','Curry leaves','Oil','Salt'], steps:['Heat oil and add curry leaves and onion.','Add chicken, pepper, and salt, and cook on medium heat.','Add mushrooms and continue stirring until tender.','Cook until the moisture reduces and flavors concentrate.','Serve hot with rice or roti.']},
  {name:'Chicken Biryani', cuisine:'Indian', diet:'Non-Veg', time:'60 min', serves:'2', desc:'Fragrant layered rice with spiced chicken.', ingredients:['250g chicken','1.5 cups rice','1 onion','Yogurt','Biryani masala','Mint','Coriander','Saffron or food color','Oil, salt'], steps:['Marinate chicken with yogurt, biryani masala, onion, and herbs.','Partially cook the rice until 70 percent done.','Layer chicken and rice in a heavy pot.','Add mint, coriander, and saffron water, then cover tightly.','Cook on low heat until done and serve with raita.']},
  {name:'Chole Rice', cuisine:'Indian', diet:'Veg', time:'40 min', serves:'2', desc:'Punjabi chickpea curry with rice.', ingredients:['1 cup chickpeas','1 onion','2 tomatoes','Chole masala','Ginger garlic paste','Rice','Salt','Oil'], steps:['Soak and boil chickpeas until soft.','Prepare onion-tomato masala with ginger garlic paste and spices.','Add chickpeas and simmer until thick and flavorful.','Serve with steamed rice.']},
  {name:'Dal Makhani + Jeera Rice', cuisine:'Indian', diet:'Veg', time:'50 min', serves:'2', desc:'Creamy black lentils with cumin rice.', ingredients:['1/2 cup black lentils','2 tbsp kidney beans','1 onion','1 tomato','Butter','Cream','Rice','Cumin','Salt'], steps:['Soak and cook lentils and kidney beans until soft.','Make a rich onion-tomato base with butter and spices.','Add cooked lentils and simmer slowly.','Finish with cream. Serve with jeera rice.']}
];
const state = { q:'', cuisine:'All', diet:'All', activeId:null };
const cuisineFilters = document.getElementById('cuisineFilters');
const dietFilters = document.getElementById('dietFilters');
const searchInput = document.getElementById('searchInput');
const mealGrid = document.getElementById('mealGrid');
const countText = document.getElementById('countText');
const statusBox = document.getElementById('statusBox');
const modal = document.getElementById('modal');
const modalTitle = document.getElementById('modalTitle');
const modalMeta = document.getElementById('modalMeta');
const modalDescription = document.getElementById('modalDescription');
const modalQuick = document.getElementById('modalQuick');
const modalIngredients = document.getElementById('modalIngredients');
const modalSteps = document.getElementById('modalSteps');
const cuisines = ['All', ...new Set(meals.map(m => m.cuisine))];
const diets = ['All', 'Veg', 'Non-Veg'];
function pillSet(root, items, key){ root.innerHTML=''; items.forEach(item=>{ const b=document.createElement('button'); b.type='button'; b.className='pill'+(state[key]===item?' active':''); b.textContent=item; b.addEventListener('click',()=>{ state[key]=item; updateUI(); status(`${key==='cuisine'?'Cuisine':'Diet'}: ${item}`); }); root.appendChild(b); }); }
function status(text){ statusBox.textContent=text; }
function filtered(){ return meals.filter(m=>{ const t=(m.name+' '+m.cuisine+' '+m.diet+' '+m.desc+' '+m.ingredients.join(' ')+' '+m.steps.join(' ')).toLowerCase(); return (state.cuisine==='All'||m.cuisine===state.cuisine) && (state.diet==='All'||m.diet===state.diet) && (!state.q || t.includes(state.q.toLowerCase())); }); }
function renderCards(list){ mealGrid.innerHTML = list.length ? list.map(m=>`<article class="card recipe-card${state.activeId===m.name?' active':''}" data-name="${encodeURIComponent(m.name)}" tabindex="0" role="button" aria-label="Open ${m.name}"><div class="topline"><h3 class="title">${m.name}</h3></div><div class="meta"><span class="tag accent">${m.cuisine}</span><span class="tag ${m.diet==='Veg'?'green':'orange'}">${m.diet}</span><span class="tag">${m.time}</span></div><p class="desc">${m.desc}</p></article>`).join('') : '<div class="empty">No recipes found. Try changing filters or search.</div>'; document.querySelectorAll('.recipe-card').forEach(el=>{ const open=()=>openMeal(decodeURIComponent(el.dataset.name)); el.addEventListener('click',open); el.addEventListener('keydown',e=>{ if(e.key==='Enter'||e.key===' '){ e.preventDefault(); open(); } }); }); countText.textContent = `${list.length} recipe${list.length===1?'':'s'} visible`; }
function openMeal(name){ const m=meals.find(x=>x.name===name); if(!m) return; state.activeId=m.name; modalTitle.textContent=m.name; modalMeta.innerHTML=`<span class="tag accent">${m.cuisine}</span><span class="tag ${m.diet==='Veg'?'green':'orange'}">${m.diet}</span><span class="tag">${m.time}</span><span class="tag">Serves ${m.serves}</span>`; modalDescription.textContent=m.desc; modalQuick.innerHTML=`<span class="tag">Ingredients: ${m.ingredients.length}</span><span class="tag">Steps: ${m.steps.length}</span>`; modalIngredients.innerHTML=m.ingredients.map(i=>`<li>${i}</li>`).join(''); modalSteps.innerHTML=m.steps.map(s=>`<li>${s}</li>`).join(''); modal.classList.add('open'); modal.setAttribute('aria-hidden','false'); renderCards(filtered()); status(`${m.name} opened`); }
function closeMeal(){ modal.classList.remove('open'); modal.setAttribute('aria-hidden','true'); }
function updateUI(){ pillSet(cuisineFilters,cuisines,'cuisine'); pillSet(dietFilters,diets,'diet'); renderCards(filtered()); }
function reset(){ state.q=''; state.cuisine='All'; state.diet='All'; state.activeId=null; searchInput.value=''; updateUI(); status('Showing all recipes.'); }
function randomMeal(){ const list=filtered(); const pick=list[Math.floor(Math.random()*list.length)] || meals[Math.floor(Math.random()*meals.length)]; if(!pick) return; openMeal(pick.name); status(`Random pick: ${pick.name}`); }
searchInput.addEventListener('input',e=>{ state.q=e.target.value.trim(); updateUI(); status(state.q ? `Search: ${state.q}` : 'Search cleared.'); });
document.getElementById('rollBtn').addEventListener('click',randomMeal); document.getElementById('resetBtn').addEventListener('click',reset);
document.getElementById('closeModal').addEventListener('click',closeMeal); modal.addEventListener('click',e=>{ if(e.target===modal) closeMeal(); });
document.getElementById('rollBtn').addEventListener('click',()=>{ const list=filtered(); if(list.length){ const pick=list[Math.floor(Math.random()*list.length)]; openMeal(pick.name); } else { status('No filtered recipes.'); } });
if (document.body){ reset(); }
const themeToggle = document.createElement('button');
themeToggle.type = 'button';
themeToggle.className = 'btn btn-secondary';
themeToggle.textContent = 'Dark mode';
themeToggle.style.marginTop = '10px';
document.querySelector('.controls').appendChild(themeToggle);
const root = document.documentElement;
let dark = false;
themeToggle.addEventListener('click', () => { dark = !dark; root.setAttribute('data-theme', dark ? 'dark' : 'light'); themeToggle.textContent = dark ? 'Light mode' : 'Dark mode'; status(dark ? 'Dark mode on.' : 'Light mode on.'); });
